name: Node.js CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm install
      - run: npm test